version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    container_name: frontend-container

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    container_name: backend-container
    environment:
      - NODE_ENV=production